version: '3.9'

services:
  dbtest:
    image: postgres:15.3
    restart: always
    container_name: integration-tests
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  dblocal:
    image: postgres:15.3
    env_file: .env
    restart: always
    container_name: local-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: db
